Added missing sexplib/comparelib syntax deps.
On a fresh clone of this repository, if you run `make` (as instructed by
the README), you get the following errors:

```
ocaml setup.ml -build -j 4
File "_tags", line 18, characters 26-43:
Warning: the tag "use_netkat_decide" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
File "_tags", line 33, characters 16-30:
Warning: the tag "syntax_camlp4o" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
+ ocamlfind ocamldep -package threads -package tdk -package sexplib -package core -package comparelib -package sexplib.syntax -package comparelib.syntax -modules src/Decide_Util.mli > src/Decide_Util.mli.depends
File "src/Decide_Util.mli", line 17, characters 9-13:
Error: Syntax error
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
E: Failure("Command ''/usr/bin/ocamlbuild' src/netkat_decide.cma src/netkat_decide.cmxa src/netkat_decide.a src/netkat_decide.cmxs src/Decide_Repl.native -use-ocamlfind -tag debug -j 4' terminated with error code 10")
make: *** [build] Error 1
```

Line 17 of `src/Decide_Util.mli` is

```ocaml
type t with sexp
```

Oasis didn't understand the `with sexp` annotation because it was
missing the sexplib syntax extensions. With this commit, the code builds
cleanly.